In [46]:
import numpy as np
import math

In [58]:
def tanh(x):
    return np.tanh(x)

def softmax(x):
    exp=np.exp(x-x.max())
    return exp/exp.sum()

In [59]:
softmax(np.array([1,2,3,4]))

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [66]:
dinensions=[28*28,10]
activation=[tanh,softmax]
distribution=[{'b':[0,0]},
              {'b':[0,0],'w':[-math.sqrt(6/(dinensions[0]+dinensions[1])),math.sqrt(6/(dinensions[0]+dinensions[1]))]}]

In [70]:
def init_parameters_b(layer):
    dist=distribution[layer]['b']
    return np.random.rand(dinensions[layer])*(dist[1]-dist[0])+dist[0]  #使得生成的随机数在 b 的区间内

def init_parameters_w(layer):
    dist=distribution[layer]['w']
    return np.random.rand(dinensions[layer-1],dinensions[layer])*(dist[1]-dist[0])+dist[0]  #使得生成的随机数在 b 的区间内

In [71]:
init_parameters_w(1) #为什么是二维数组？

array([[ 0.01076475,  0.02776912, -0.01154034, ..., -0.00442505,
        -0.06225646, -0.06328143],
       [-0.01434044,  0.06877749,  0.00458292, ...,  0.03342906,
         0.03741978, -0.06291372],
       [ 0.05557037, -0.08447513,  0.03971868, ..., -0.05137621,
         0.00109148,  0.07518763],
       ...,
       [-0.04591683, -0.00429465,  0.03709094, ..., -0.05067353,
         0.04192851, -0.05198389],
       [-0.07376785,  0.07343643,  0.03211347, ...,  0.08687076,
         0.06617992, -0.07663586],
       [ 0.00737799,  0.05878906,  0.00035766, ..., -0.03646365,
         0.02329599, -0.03471394]])

array([[0.83731017, 0.8184871 , 0.54839397, ..., 0.22525514, 0.94125926,
        0.72159737],
       [0.6339734 , 0.24232286, 0.62528729, ..., 0.47868076, 0.33889996,
        0.53674205],
       [0.94812739, 0.04994936, 0.41991164, ..., 0.78058553, 0.50003702,
        0.31466131],
       ...,
       [0.73933008, 0.47432517, 0.52700977, ..., 0.47806987, 0.22448078,
        0.63209947],
       [0.54097611, 0.17282202, 0.17863888, ..., 0.48121024, 0.10582687,
        0.48673245],
       [0.84849426, 0.84043971, 0.02193476, ..., 0.59893318, 0.64934097,
        0.34976927]])

In [96]:
def init_parameters():
    parameters=[]
    for i in range(len(distribution)):
        layer_parameters={}
        for j in distribution[i].keys(): 
            if j=='b':
                layer_parameters['b']=init_parameters_b(i)
                continue
            if j=='w':
                layer_parameters['w']=init_parameters_w(i)
                continue
        parameters.append(layer_parameters)
    return parameters

In [97]:
init_parameters()

[{'b': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [98]:
parameters=init_parameters()

In [103]:
def predict(img,parameters):
    I0_in=img+parameters[0]['b']
    I0_out=activation[0](I0_in)
    I1_in=np.dot(I0_out,parameters[1]['w']+parameters[1]['b'])
    I1_out=activation[1](I1_in)
    return I1_out

In [108]:
predict(np.random.rand(784),parameters).argmax()

1